const Events = {
	CREATED_UPDATED: 0,
	WON_UPDATED: 1,
	MESSAGES_UPDATED: 2,
	POINTS_UPDATED: 3,
	LEVEL_UPDATED: 4,
	WISHLIST_UPDATED: 5,
	REPUTATION_UPDATED: 6,
	PAGE_REFRESHED: 7,
	HEADER_REFRESHED: 8,
	NOTIFICATION_BAR_BUILD: 9,
	BUTTON_BUILD: 10,
	PAGE_HEADING_BUILD: 11,
	GIVEAWAY_ENTER: 12,
	GIVEAWAY_LEAVE: 13,
};

export { Events };
